### ISSUE TITLE
`raco make ulqui` fails

### ISSUE THREAD

**Issue by cmpitg** [cmpitg/ulquikit#36]
```
resolve-path: contract violation
  expected: path-string?
  given: #f
  context...:
   /home/cmpitg/opt/ulquikit/bin/ulqui: [running body]
```

It fails because `(syntax-source #'here)` returns `#f`, which `resolve-path` doesn't accept as its arg.
